import { useState } from "react";
import "./Contact.css";

function Contact() {
  const [formData, setFormData] = useState({ name: "", email: "", message: "" });
    const [submitted, setSubmitted] = useState(false);
      const [error, setError] = useState("");

        function handleChange(e) {
            setFormData({ ...formData, [e.target.name]: e.target.value });
              }

                function handleSubmit(e) {
                    e.preventDefault();
                        if (!formData.name || !formData.email || !formData.message) {
                              setError("Please fill in all fields.");
                                    return;
                                        }
                                            setError("");
                                                setSubmitted(true);
                                                  }

                                                    return (
                                                        <div className="contact-page">
                                                              <div className="contact-header">
                                                                      <h1>Contact Us 📬</h1>
                                                                              <p>Have a question or suggestion? We'd love to hear from you.</p>
                                                                                    </div>

                                                                                          <div className="contact-container">
                                                                                                  <div className="contact-info">
                                                                                                            <h3>Get In Touch</h3>
                                                                                                                      <div className="info-item"><span>📧</span><p>interviewprep@email.com</p></div>
                                                                                                                                <div className="info-item"><span>🏫</span><p>Software Engineering Department</p></div>
                                                                                                                                          <div className="info-item"><span>📅</span><p>Project Deadline: June 12, 2026</p></div>
                                                                                                                                                    <div className="info-item"><span>🌍</span><p>Built with React · Deployed on Vercel</p></div>
                                                                                                                                                            </div>

                                                                                                                                                                    <div className="contact-form-box">
                                                                                                                                                                              {submitted ? (
                                                                                                                                                                                          <div className="success-message">
                                                                                                                                                                                                        <span>✅</span>
                                                                                                                                                                                                                      <h3>Message Sent!</h3>
                                                                                                                                                                                                                                    <p>Thank you, {formData.name}! We'll get back to you soon.</p>
                                                                                                                                                                                                                                                  <button onClick={() => { setSubmitted(false); setFormData({ name: "", email: "", message: "" }); }}>
                                                                                                                                                                                                                                                                  Send Another
                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                  <>
                                                                                                                                                                                                                                                                                                                                {error && <div className="contact-error">{error}</div>}
                                                                                                                                                                                                                                                                                                                                              <form onSubmit={handleSubmit}>
                                                                                                                                                                                                                                                                                                                                                              <div className="form-group">
                                                                                                                                                                                                                                                                                                                                                                                <label>Full Name</label>
                                                                                                                                                                                                                                                                                                                                                                                                  <input type="text" name="name" placeholder="Your full name" value={formData.name} onChange={handleChange} />
                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="form-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label>Email Address</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input type="email" name="email" placeholder="Your email" value={formData.email} onChange={handleChange} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="form-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label>Message</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <textarea name="message" placeholder="Write your message here..." rows="5" value={formData.message} onChange={handleChange}></textarea>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button type="submit" className="contact-btn">Send Message 📨</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default Contact;