import { useState, useEffect } from "react";
import { Link, useNavigate } from "react-router-dom";
import "./Dashboard.css";

function Dashboard() {
  const navigate = useNavigate();
    const [user, setUser] = useState(null);
      const [results, setResults] = useState([]);
        const [loading, setLoading] = useState(true);

          useEffect(() => {
              const loggedIn = localStorage.getItem("loggedIn");
                  if (!loggedIn) {
                        navigate("/login");
                              return;
                                  }

                                      const savedUser = JSON.parse(localStorage.getItem("user"));
                                          const savedResults = JSON.parse(localStorage.getItem("results")) || [];

                                              setUser(savedUser);
                                                  setResults(savedResults);
                                                      setLoading(false);
                                                        }, [navigate]);

                                                          function handleLogout() {
                                                              localStorage.removeItem("loggedIn");
                                                                  navigate("/login");
                                                                    }

                                                                      if (loading) return <div className="loading">Loading dashboard...</div>;

                                                                        const totalTests = results.length;
                                                                          const avgScore = totalTests > 0
                                                                              ? Math.round(results.reduce((sum, r) => sum + r.score, 0) / totalTests)
                                                                                  : 0;
                                                                                    const bestScore = totalTests > 0
                                                                                        ? Math.max(...results.map(r => r.score))
                                                                                            : 0;

                                                                                              return (
                                                                                                  <div className="dashboard">

                                                                                                        {/* Header */}
                                                                                                              <div className="dash-header">
                                                                                                                      <div>
                                                                                                                                <h1>Welcome back, {user?.name} 👋</h1>
                                                                                                                                          <p>Keep practicing — you're getting better every day!</p>
                                                                                                                                                  </div>
                                                                                                                                                          <button className="logout-btn" onClick={handleLogout}>Logout</button>
                                                                                                                                                                </div>

                                                                                                                                                                      {/* Stats */}
                                                                                                                                                                            <div className="dash-stats">
                                                                                                                                                                                    <div className="dash-stat-card">
                                                                                                                                                                                              <h3>{totalTests}</h3>
                                                                                                                                                                                                        <p>Tests Taken</p>
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                        <div className="dash-stat-card">
                                                                                                                                                                                                                                  <h3>{avgScore}%</h3>
                                                                                                                                                                                                                                            <p>Average Score</p>
                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                            <div className="dash-stat-card">
                                                                                                                                                                                                                                                                      <h3>{bestScore}%</h3>
                                                                                                                                                                                                                                                                                <p>Best Score</p>
                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                    {/* Quick Actions */}
                                                                                                                                                                                                                                                                                                          <div className="dash-actions">
                                                                                                                                                                                                                                                                                                                  <h2>Quick Actions</h2>
                                                                                                                                                                                                                                                                                                                          <div className="action-cards">
                                                                                                                                                                                                                                                                                                                                    <Link to="/mock-test" className="action-card">
                                                                                                                                                                                                                                                                                                                                                <span>⏱️</span>
                                                                                                                                                                                                                                                                                                                                                            <h3>Start Mock Test</h3>
                                                                                                                                                                                                                                                                                                                                                                        <p>Test yourself under timed conditions</p>
                                                                                                                                                                                                                                                                                                                                                                                  </Link>
                                                                                                                                                                                                                                                                                                                                                                                            <Link to="/questions" className="action-card">
                                                                                                                                                                                                                                                                                                                                                                                                        <span>📚</span>
                                                                                                                                                                                                                                                                                                                                                                                                                    <h3>Browse Questions</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                <p>Study questions by topic and difficulty</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link to="/topics" className="action-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span>🗂️</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3>View Topics</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Explore all interview categories</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link to="/profile" className="action-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>👤</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3>My Profile</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>View and edit your profile info</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Recent Results */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="dash-history">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2>Recent Test History</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {results.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="no-results">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>You haven't taken any tests yet.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Link to="/mock-test" className="btn-primary">Take Your First Test</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <table className="results-table">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <th>Date</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <th>Category</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <th>Score</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <th>Result</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {results.slice().reverse().map((r, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <tr key={i}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td>{r.date}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td>{r.category}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td>{r.score}%</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className={r.score >= 50 ? "badge pass" : "badge fail"}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {r.score >= 50 ? "Pass" : "Fail"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default Dashboard;