import { Link } from "react-router-dom";
import "./Home.css";

function Home() {
  return (
      <div className="home">

            {/* Hero Section */}
                  <section className="hero">
                          <h1>Ace Your Next Interview 🚀</h1>
                                  <p>Practice real interview questions, take mock tests, and track your progress — all in one place.</p>
                                          <div className="hero-buttons">
                                                    <Link to="/mock-test" className="btn-primary">Start Mock Test</Link>
                                                              <Link to="/topics" className="btn-secondary">Browse Topics</Link>
                                                                      </div>
                                                                            </section>

                                                                                  {/* Stats Section */}
                                                                                        <section className="stats">
                                                                                                <div className="stat-card">
                                                                                                          <h2>200+</h2>
                                                                                                                    <p>Interview Questions</p>
                                                                                                                            </div>
                                                                                                                                    <div className="stat-card">
                                                                                                                                              <h2>10+</h2>
                                                                                                                                                        <p>Topic Categories</p>
                                                                                                                                                                </div>
                                                                                                                                                                        <div className="stat-card">
                                                                                                                                                                                  <h2>Free</h2>
                                                                                                                                                                                            <p>Always Free to Use</p>
                                                                                                                                                                                                    </div>
                                                                                                                                                                                                          </section>

                                                                                                                                                                                                                {/* Features Section */}
                                                                                                                                                                                                                      <section className="features">
                                                                                                                                                                                                                              <h2>Why Use InterviewPrep?</h2>
                                                                                                                                                                                                                                      <div className="feature-cards">
                                                                                                                                                                                                                                                <div className="feature-card">
                                                                                                                                                                                                                                                            <span>🧠</span>
                                                                                                                                                                                                                                                                        <h3>Real Questions</h3>
                                                                                                                                                                                                                                                                                    <p>Questions from real interviews in tech, covering React, JavaScript, HTML, CSS and more.</p>
                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                        <div className="feature-card">
                                                                                                                                                                                                                                                                                                                    <span>⏱️</span>
                                                                                                                                                                                                                                                                                                                                <h3>Timed Mock Tests</h3>
                                                                                                                                                                                                                                                                                                                                            <p>Simulate real interview pressure with our timed mock test mode.</p>
                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                <div className="feature-card">
                                                                                                                                                                                                                                                                                                                                                                            <span>📊</span>
                                                                                                                                                                                                                                                                                                                                                                                        <h3>Track Progress</h3>
                                                                                                                                                                                                                                                                                                                                                                                                    <p>See your scores, improvement and history on your personal dashboard.</p>
                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="feature-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                    <span>📱</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3>Works Everywhere</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>Fully responsive — use it on your phone, tablet or laptop.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* CTA Section */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <section className="cta">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2>Ready to start practicing?</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>Create a free account and begin your interview preparation today.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link to="/register" className="btn-primary">Get Started Free</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default Home;