import { useState, useEffect } from "react";
import { useSearchParams, useNavigate } from "react-router-dom";
import allQuestions from "../data/questions.json";
import "./MockTest.css";

function MockTest() {
  const [searchParams] = useSearchParams();
    const navigate = useNavigate();
      const category = searchParams.get("category") || "All";

        const [questions, setQuestions] = useState([]);
          const [current, setCurrent] = useState(0);
            const [selected, setSelected] = useState(null);
              const [score, setScore] = useState(0);
                const [timeLeft, setTimeLeft] = useState(30);
                  const [finished, setFinished] = useState(false);
                    const [answers, setAnswers] = useState([]);
                      const [started, setStarted] = useState(false);

                        // Filter and shuffle questions
                          useEffect(() => {
                              const filtered = category === "All"
                                    ? allQuestions
                                          : allQuestions.filter((q) => q.category === category);

                                              const shuffled = filtered.sort(() => Math.random() - 0.5).slice(0, 10);
                                                  setQuestions(shuffled);
                                                    }, [category]);

                                                      // Timer
                                                        useEffect(() => {
                                                            if (!started || finished) return;

                                                                if (timeLeft === 0) {
                                                                      handleNext(true);
                                                                            return;
                                                                                }

                                                                                    const timer = setInterval(() => {
                                                                                          setTimeLeft((prev) => prev - 1);
                                                                                              }, 1000);

                                                                                                  return () => clearInterval(timer);
                                                                                                    }, [timeLeft, started, finished]);

                                                                                                      function handleSelect(option) {
                                                                                                          if (selected !== null) return;
                                                                                                              setSelected(option);
                                                                                                                }

                                                                                                                  function handleNext(timeout = false) {
                                                                                                                      const currentQ = questions[current];
                                                                                                                          const isCorrect = !timeout && selected === currentQ.answer;

                                                                                                                              const newAnswers = [...answers, {
                                                                                                                                    question: currentQ.question,
                                                                                                                                          selected: timeout ? "No Answer (Time Up)" : selected,
                                                                                                                                                correct: currentQ.answer,
                                                                                                                                                      isCorrect,
                                                                                                                                                          }];

                                                                                                                                                              setAnswers(newAnswers);
                                                                                                                                                                  if (isCorrect) setScore((prev) => prev + 1);

                                                                                                                                                                      if (current + 1 >= questions.length) {
                                                                                                                                                                            finishTest(newAnswers, isCorrect ? score + 1 : score);
                                                                                                                                                                                } else {
                                                                                                                                                                                      setCurrent((prev) => prev + 1);
                                                                                                                                                                                            setSelected(null);
                                                                                                                                                                                                  setTimeLeft(30);
                                                                                                                                                                                                      }
                                                                                                                                                                                                        }

                                                                                                                                                                                                          function finishTest(finalAnswers, finalScore) {
                                                                                                                                                                                                              setFinished(true);
                                                                                                                                                                                                                  const percent = Math.round((finalScore / questions.length) * 100);

                                                                                                                                                                                                                      // Save result to localStorage
                                                                                                                                                                                                                          const results = JSON.parse(localStorage.getItem("results")) || [];
                                                                                                                                                                                                                              results.push({
                                                                                                                                                                                                                                    date: new Date().toLocaleDateString(),
                                                                                                                                                                                                                                          category: category,
                                                                                                                                                                                                                                                score: percent,
                                                                                                                                                                                                                                                      total: questions.length,
                                                                                                                                                                                                                                                            correct: finalScore,
                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                    localStorage.setItem("results", JSON.stringify(results));

                                                                                                                                                                                                                                                                        // Pass data to Results page
                                                                                                                                                                                                                                                                            localStorage.setItem("lastResult", JSON.stringify({
                                                                                                                                                                                                                                                                                  score: percent,
                                                                                                                                                                                                                                                                                        correct: finalScore,
                                                                                                                                                                                                                                                                                              total: questions.length,
                                                                                                                                                                                                                                                                                                    category,
                                                                                                                                                                                                                                                                                                          answers: finalAnswers,
                                                                                                                                                                                                                                                                                                              }));

                                                                                                                                                                                                                                                                                                                  navigate("/results");
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                      function startTest() {
                                                                                                                                                                                                                                                                                                                          setStarted(true);
                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                              // Generate options for each question
                                                                                                                                                                                                                                                                                                                                function getOptions(q) {
                                                                                                                                                                                                                                                                                                                                    const wrong = allQuestions
                                                                                                                                                                                                                                                                                                                                          .filter((item) => item.answer !== q.answer)
                                                                                                                                                                                                                                                                                                                                                .sort(() => Math.random() - 0.5)
                                                                                                                                                                                                                                                                                                                                                      .slice(0, 3)
                                                                                                                                                                                                                                                                                                                                                            .map((item) => item.answer);
                                                                                                                                                                                                                                                                                                                                                                return [...wrong, q.answer].sort(() => Math.random() - 0.5);
                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                    if (questions.length === 0) return <div className="loading">Loading questions...</div>;

                                                                                                                                                                                                                                                                                                                                                                      // Start Screen
                                                                                                                                                                                                                                                                                                                                                                        if (!started) {
                                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                                  <div className="test-start">
                                                                                                                                                                                                                                                                                                                                                                                          <div className="start-card">
                                                                                                                                                                                                                                                                                                                                                                                                    <span className="start-icon">⏱️</span>
                                                                                                                                                                                                                                                                                                                                                                                                              <h2>Mock Interview Test</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Category: <strong>{category}</strong></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <ul className="test-rules">
                                                                                                                                                                                                                                                                                                                                                                                                                                              <li>✅ {Math.min(10, questions.length)} questions total</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <li>⏱️ 30 seconds per question</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <li>❌ Unanswered questions count as wrong</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <li>📊 Results saved to your dashboard</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button className="start-btn" onClick={startTest}>Start Test</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const currentQ = questions[current];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const options = getOptions(currentQ);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const progress = ((current) / questions.length) * 100;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const timerColor = timeLeft <= 10 ? "#e94560" : "#2ecc71";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mock-test">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Top Bar */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="test-topbar">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="test-progress-text">Question {current + 1} of {questions.length}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="test-category">{category}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="test-timer" style={{ color: timerColor }}>⏱️ {timeLeft}s</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Progress Bar */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="test-progress-bar">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="test-progress-fill" style={{ width: `${progress}%` }}></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Question */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="test-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="test-question">{currentQ.question}</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="test-options">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {options.map((option, i) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              let cls = "option-btn";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (selected !== null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (option === currentQ.answer) cls += " correct";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      else if (option === selected) cls += " wrong";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button key={i} className={cls} onClick={() => handleSelect(option)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="option-letter">{String.fromCharCode(65 + i)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {option}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {selected !== null && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="answer-feedback">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {selected === currentQ.answer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ? "✅ Correct! Well done."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : `❌ Wrong. The correct answer is highlighted above.`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="next-btn"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => handleNext(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          disabled={selected === null}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {current + 1 === questions.length ? "Finish Test" : "Next Question →"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Score tracker */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="score-tracker">Current Score: {score}/{current}</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default MockTest;