import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import "./Profile.css";

function Profile() {
  const navigate = useNavigate();
    const [user, setUser] = useState({ name: "", email: "" });
      const [editing, setEditing] = useState(false);
        const [formData, setFormData] = useState({ name: "", email: "" });
          const [saved, setSaved] = useState(false);
            const [results, setResults] = useState([]);

              useEffect(() => {
                  const loggedIn = localStorage.getItem("loggedIn");
                      if (!loggedIn) { navigate("/login"); return; }
                          const savedUser = JSON.parse(localStorage.getItem("user"));
                              const savedResults = JSON.parse(localStorage.getItem("results")) || [];
                                  setUser(savedUser);
                                      setFormData({ name: savedUser.name, email: savedUser.email });
                                          setResults(savedResults);
                                            }, [navigate]);

                                              function handleChange(e) {
                                                  setFormData({ ...formData, [e.target.name]: e.target.value });
                                                    }

                                                      function handleSave() {
                                                          const updated = { ...user, ...formData };
                                                              localStorage.setItem("user", JSON.stringify(updated));
                                                                  setUser(updated);
                                                                      setEditing(false);
                                                                          setSaved(true);
                                                                              setTimeout(() => setSaved(false), 3000);
                                                                                }

                                                                                  const totalTests = results.length;
                                                                                    const avgScore = totalTests > 0
                                                                                        ? Math.round(results.reduce((sum, r) => sum + r.score, 0) / totalTests)
                                                                                            : 0;

                                                                                              return (
                                                                                                  <div className="profile-page">

                                                                                                        {/* Profile Card */}
                                                                                                              <div className="profile-card">
                                                                                                                      <div className="profile-avatar">
                                                                                                                                {user.name ? user.name.charAt(0).toUpperCase() : "?"}
                                                                                                                                        </div>
                                                                                                                                                <h2>{user.name}</h2>
                                                                                                                                                        <p className="profile-email">{user.email}</p>

                                                                                                                                                                <div className="profile-stats">
                                                                                                                                                                          <div className="profile-stat">
                                                                                                                                                                                      <h4>{totalTests}</h4>
                                                                                                                                                                                                  <p>Tests Taken</p>
                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                      <div className="profile-stat">
                                                                                                                                                                                                                                  <h4>{avgScore}%</h4>
                                                                                                                                                                                                                                              <p>Avg Score</p>
                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                  <div className="profile-stat">
                                                                                                                                                                                                                                                                              <h4>{totalTests > 0 ? Math.max(...results.map(r => r.score)) : 0}%</h4>
                                                                                                                                                                                                                                                                                          <p>Best Score</p>
                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                    {saved && <div className="save-success">✅ Profile updated successfully!</div>}

                                                                                                                                                                                                                                                                                                                            {!editing ? (
                                                                                                                                                                                                                                                                                                                                      <button className="edit-btn" onClick={() => setEditing(true)}>Edit Profile</button>
                                                                                                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                                                                                                        <div className="edit-form">
                                                                                                                                                                                                                                                                                                                                                                    <div className="form-group">
                                                                                                                                                                                                                                                                                                                                                                                  <label>Full Name</label>
                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                name="name"
                                                                                                                                                                                                                                                                                                                                                                                                                                                value={formData.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="form-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label>Email Address</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  name="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  value={formData.email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="edit-buttons">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button className="save-btn" onClick={handleSave}>Save Changes</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button className="cancel-btn" onClick={() => setEditing(false)}>Cancel</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Test History */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="profile-history">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2>Test History</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {results.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="no-history">No tests taken yet. <a href="/mock-test">Take your first test!</a></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="history-list">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {results.slice().reverse().map((r, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="history-item" key={i}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="history-left">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="history-category">{r.category}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="history-date">{r.date}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="history-right">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="history-score">{r.score}%</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className={`history-badge ${r.score >= 50 ? "pass" : "fail"}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {r.score >= 50 ? "Pass" : "Fail"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default Profile;