import { useState, useEffect } from "react";
import { useSearchParams } from "react-router-dom";
import allQuestions from "../data/questions.json";
import "./Questions.css";

const categories = ["All", "React", "JavaScript", "HTML", "CSS", "General"];
const difficulties = ["All", "Easy", "Medium", "Hard"];

function Questions() {
  const [searchParams] = useSearchParams();
    const [search, setSearch] = useState("");
      const [category, setCategory] = useState(searchParams.get("category") || "All");
        const [difficulty, setDifficulty] = useState("All");
          const [expanded, setExpanded] = useState(null);

            useEffect(() => {
                const cat = searchParams.get("category");
                    if (cat) setCategory(cat);
                      }, [searchParams]);

                        const filtered = allQuestions.filter((q) => {
                            const matchCategory = category === "All" || q.category === category;
                                const matchDifficulty = difficulty === "All" || q.difficulty === difficulty;
                                    const matchSearch = q.question.toLowerCase().includes(search.toLowerCase());
                                        return matchCategory && matchDifficulty && matchSearch;
                                          });

                                            function toggleExpand(id) {
                                                setExpanded(expanded === id ? null : id);
                                                  }

                                                    return (
                                                        <div className="questions-page">
                                                              <div className="questions-header">
                                                                      <h1>Interview Questions 📚</h1>
                                                                              <p>Browse, filter and study questions by topic and difficulty</p>
                                                                                    </div>

                                                                                          {/* Filters */}
                                                                                                <div className="filters">
                                                                                                        <input
                                                                                                                  type="text"
                                                                                                                            placeholder="🔍 Search questions..."
                                                                                                                                      value={search}
                                                                                                                                                onChange={(e) => setSearch(e.target.value)}
                                                                                                                                                          className="search-input"
                                                                                                                                                                  />
                                                                                                                                                                          <div className="filter-buttons">
                                                                                                                                                                                    {categories.map((cat) => (
                                                                                                                                                                                                <button
                                                                                                                                                                                                              key={cat}
                                                                                                                                                                                                                            className={`filter-btn ${category === cat ? "active" : ""}`}
                                                                                                                                                                                                                                          onClick={() => setCategory(cat)}
                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                    {cat}
                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                          <div className="filter-buttons">
                                                                                                                                                                                                                                                                                                                    {difficulties.map((diff) => (
                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                              key={diff}
                                                                                                                                                                                                                                                                                                                                                            className={`filter-btn diff ${difficulty === diff ? "active" : ""}`}
                                                                                                                                                                                                                                                                                                                                                                          onClick={() => setDifficulty(diff)}
                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                    {diff}
                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Results count */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="results-count">{filtered.length} question{filtered.length !== 1 ? "s" : ""} found</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Questions List */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="questions-list">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {filtered.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="no-questions">No questions match your search.</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    filtered.map((q) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="question-card" key={q.id}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="question-top" onClick={() => toggleExpand(q.id)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="question-meta">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="q-category">{q.category}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className={`q-difficulty ${q.difficulty.toLowerCase()}`}>{q.difficulty}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="q-text">{q.question}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="q-toggle">{expanded === q.id ? "▲ Hide Answer" : "▼ Show Answer"}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {expanded === q.id && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="question-answer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <strong>Answer:</strong> {q.answer}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default Questions;