import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import "./Auth.css";

function Register() {
  const navigate = useNavigate();
    const [formData, setFormData] = useState({ name: "", email: "", password: "", confirm: "" });
      const [error, setError] = useState("");
        const [loading, setLoading] = useState(false);

          function handleChange(e) {
              setFormData({ ...formData, [e.target.name]: e.target.value });
                }

                  function handleSubmit(e) {
                      e.preventDefault();
                          setError("");

                              if (!formData.name || !formData.email || !formData.password || !formData.confirm) {
                                    setError("Please fill in all fields.");
                                          return;
                                              }

                                                  if (formData.password !== formData.confirm) {
                                                        setError("Passwords do not match.");
                                                              return;
                                                                  }

                                                                      if (formData.password.length < 6) {
                                                                            setError("Password must be at least 6 characters.");
                                                                                  return;
                                                                                      }

                                                                                          setLoading(true);

                                                                                              // Save user to localStorage
                                                                                                  const user = { name: formData.name, email: formData.email, password: formData.password };
                                                                                                      localStorage.setItem("user", JSON.stringify(user));
                                                                                                          localStorage.setItem("loggedIn", "true");

                                                                                                              setLoading(false);
                                                                                                                  navigate("/dashboard");
                                                                                                                    }

                                                                                                                      return (
                                                                                                                          <div className="auth-page">
                                                                                                                                <div className="auth-card">
                                                                                                                                        <h2>Create Account 🎯</h2>
                                                                                                                                                <p className="auth-subtitle">Join and start preparing for your dream job</p>

                                                                                                                                                        {error && <div className="auth-error">{error}</div>}

                                                                                                                                                                <form onSubmit={handleSubmit}>
                                                                                                                                                                          <div className="form-group">
                                                                                                                                                                                      <label>Full Name</label>
                                                                                                                                                                                                  <input
                                                                                                                                                                                                                type="text"
                                                                                                                                                                                                                              name="name"
                                                                                                                                                                                                                                            placeholder="Enter your full name"
                                                                                                                                                                                                                                                          value={formData.name}
                                                                                                                                                                                                                                                                        onChange={handleChange}
                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                        <div className="form-group">
                                                                                                                                                                                                                                                                                                                    <label>Email Address</label>
                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                              type="email"
                                                                                                                                                                                                                                                                                                                                                            name="email"
                                                                                                                                                                                                                                                                                                                                                                          placeholder="Enter your email"
                                                                                                                                                                                                                                                                                                                                                                                        value={formData.email}
                                                                                                                                                                                                                                                                                                                                                                                                      onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="form-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label>Password</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          name="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="Create a password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      value={formData.password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="form-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label>Confirm Password</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name="confirm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="Repeat your password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={formData.confirm}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button type="submit" className="auth-btn" disabled={loading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {loading ? "Creating account..." : "Register"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="auth-switch">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Already have an account? <Link to="/login">Login here</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export default Register;